### ISSUE TITLE
Let clients connect to the server

### ISSUE THREAD

**Issue by Petoovee** [Petoovee/GroupChatV2#1]
Make sure clients can connect to the server

**Comment by Petoovee** [comment]
Currently, clients are failing at establishing their socket using the correct port , without even trying any other ports.

**Comment by Petoovee** [comment]
Same goes for localhost. Could the error reside in them not getting their streams?

**Comment by Petoovee** [comment]
```
java.net.ConnectException: Connection refused: connect
Connecting to localhost at 4473
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.doConnect(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connectToAddress(Unknown Source)
	at java.net.AbstractPlainSocketImpl.connect(Unknown Source)
	at java.net.PlainSocketImpl.connect(Unknown Source)
	at java.net.SocksSocketImpl.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.connect(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at java.net.Socket.<init>(Unknown Source)
	at client.Client.initiate(Client.java:53)
	at client.Client.run(Client.java:93)
	at client.Client.<init>(Client.java:41)
	at client.Client.main(Client.java:215)
```

> This exception means that there is no service listening on the IP/port you are trying to connect to:
> 
>     You are trying to connect to the wrong IP/port.
>     You have not started your server.
>     Your server is not listening for connections.
>     On Windows servers, the listen backlog queue is full.

**Comment by Petoovee** [comment]
The error resides on the client side, the server never sees any of the connection attempts

**Comment by Petoovee** [comment]
Ports need to be forwarded on all participating sockets
